# Generated by Django 5.1.6 on 2025-03-01 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared', to='image_manager.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_manager.user')),
            ],
        ),
    ]
