# Generated by Django 5.1.6 on 2025-03-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0004_alter_user_address_alter_user_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
